1086 - Show answer when displaying completed activity questions
wynnset/tapestry-wp pull request #1087
Opened 2021-07-22 17:54 UTC by EldadZZipori

## Changes
Add a small state machine to activity media with three states
```
const states = {
  ACTIVITY: "activity",
  ANSWER: "answer",
  COMPLETIONSCREEN: "completion-screen",
}
```

Moved the AnswerMedia component to be a part of ActivityMedia
## Screenshot
* This is a space to include a screenshot or GIF if this is a frontend change. Delete this section if this is not a frontend change.
## Issue Linkage
Closes (issue #1086 )
## PR Dependency
Depends on: N/A
## Automated Testing

1. Refactor all activities test to work with the new functionality

2021-07-26 23:15 UTC, Frozemint commented
The functionality of the feature looks fine. Could the interface be tweaked slightly so that it's more obvious to the user that they're looking at their previously entered answer? Right now it's kind of unclear:

![image](https://user-images.githubusercontent.com/11191061/127071026-c07dd16b-a4ab-45a8-b968-78619e0e8837.png)

2021-07-30 17:17 UTC, Frozemint commented
Thanks Eldad, there is a small typo with the show previous answer button, but otherwise all the core functionality as specified works and I'm happy to have the PR merged; we can worry about making more improvements to the previous answer UI later. 
![image](https://user-images.githubusercontent.com/11191061/127688900-8821d5ee-96a3-4228-92bd-2558dadec139.png)

2021-07-30 17:19 UTC, Frozemint approved these changes

2021-08-13 23:18 UTC, wynnset requested changes
This works great! Just looking at the code and had a few comments and need some clarifications so I can finish my review. In the meantime, feel free to address these comments.

2021-08-13 23:18 UTC, wynnset commented on templates/vue/src/components/Lightbox/media/ActivityMedia/index.vue
> +          style="margin-right:auto;"
```suggestion
          class="mr-auto"
```

2021-08-13 23:18 UTC, wynnset commented on templates/vue/src/components/Lightbox/media/ActivityMedia/index.vue
> +  COMPLETIONSCREEN: "completion-screen",
For better readability, please use underscore to separate the words here

2021-08-13 23:18 UTC, wynnset commented on templates/vue/src/components/Lightbox/media/ActivityMedia/index.vue
> +        : this.getNode(this.node.typeData.activityId)
Can you remind me what an activityId is exactly? I do not remember having this in the data structure. I thought we only have node Ids that are for each activity.

2021-08-13 23:18 UTC, wynnset commented on templates/vue/src/components/Lightbox/media/ActivityMedia/index.vue
> +      if (this.initialType === "activity") this.$emit("close")
Please use curly brackets for clarity and consistency.

2021-08-13 23:18 UTC, wynnset commented on templates/vue/src/components/Lightbox/media/ActivityMedia/index.vue
> +      if (sender === states.ACTIVITY) {
I find it a bit confusing to use the states for senders as well, even though they match in their string values.

2021-08-16 23:21 UTC, wynnset approved these changes

2021-08-16 23:24 UTC, merged