654 - Be told if my system, browser, or resolution does not meet the requirements
wynnset/tapestry-wp pull request #660
Opened 2020-07-28 20:15 UTC by codygagnon

Closes #654 

If the user is accessing a tapestry via Internet Explorer, a warning message should appear. Should work for Internet Explorer 10 and below (in which case the user agent will include "MSIE") and Internet Explorer 11 (in which case the user agent will include "Trident/7.0").

2020-07-30 17:47 UTC, narendrasss commented on templates/single-tapestry.php
> +    echo "<html><div>To use the Tapestry Tool, please use a browser other than Internet Explorer.</div></html>";
I think inserting this `html` tag makes it invalid HTML. Does it work if you remove the html tag?

```suggestion
    echo "<div>To use the Tapestry Tool, please use a browser other than Internet Explorer.</div>";
```

2020-08-04 21:00 UTC, wynnset commented
Let's expand the check to make sure the browser can run ES6. Some older browsers (non-IE) also cannot run ES6.

2020-08-27 01:04 UTC, codygagnon commented
> Let's expand the check to make sure the browser can run ES6. Some older browsers (non-IE) also cannot run ES6.

@wynnset Should we use feature detection? What features of ES6 should be detected?

Feature detection is recommended here: https://stackoverflow.com/questions/29046635/javascript-es6-cross-browser-detection and here: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Feature_detection

2020-09-02 19:27 UTC, wynnset requested changes

2020-09-02 19:27 UTC, wynnset commented on templates/single-tapestry.php
> +        var message = document.createTextNode(\"To use the Tapestry Tool, please use a browser that supports ES6.\")
This message is not very user friendly. Average Joe has no idea what ES6 is so we should say "Please update your browser" and list a list of links to common browser websites or instructions for updating their browsers. The messaging should be created for a very non-savvy user.

2020-09-02 21:26 UTC, wynnset commented on templates/single-tapestry.php
> +        var message = document.createTextNode(\"To use the Tapestry Tool, please use a browser that supports ES6.\")
This whole JS is better to be included as a separate JS file rather than being inserted inline.

2020-09-02 21:30 UTC, wynnset commented
Couple more things:
- It would be great to include the JS in `tapestry.php` instead the same way we are including other JS.
- Please hide the tapestry div if this test fails
- It might be nicer to put the JS fail message inside a div in `single-tapestry.php` with `display: none;` and then show it if the test fails using the script.

2020-09-03 19:12 UTC, narendrasss commented
@wynnset I added a list of older browsers and moved it to a standalone script. I decided not to move the html to `single-tapestry` because I remember Cody had issues where the document `body` wasn't even loaded (in which case no other html would be loaded as well).

@seanRong Can you test if this works? I can't test it because the older browsers don't work on latest MacOS :(

2020-09-06 07:57 UTC, wynnset approved these changes

2020-09-08 06:33 UTC, wynnset approved these changes

2020-09-08 06:44 UTC, wynnset approved these changes

2020-09-08 06:45 UTC, merged