No ticket: YouTube video in accordion appears outside of accordion
wynnset/tapestry-wp pull request #732
Opened 2020-09-13 03:35 UTC by seanRong

Note: I didn't have as large of an overflow issue without this fix, but I do believe the overflow has been reduced, this might need to be tested on the test site as well.

2020-09-24 18:24 UTC, wynnset requested changes
See comment below. Additionally, my YouTube video is appearing too narrow: 
![image](https://user-images.githubusercontent.com/8981258/94184235-7616bc00-fe58-11ea-8a7e-598661a6868d.png)

2020-09-24 18:24 UTC, wynnset commented on templates/vue/src/components/lightbox/AccordionMedia.vue
> +  overflow: hidden;
This is not working for me. When my accordion is longer than the page, it doesn't let me scroll down to see the rest of the accordion.

2020-09-26 21:06 UTC, yungalyx commented
cannot test because I'm stuck in loop during video content/ upload youtube link to node. ):

2020-09-28 05:57 UTC, seanRong commented
Tried it and it's working for me, what link did you use Alex?

Additionally, vue-youtube-embed module is giving red console errors like
```Error in callback for watcher "playerHeight": "TypeError: this.player.setSize is not a function"
```

But I'm not sure if we really want to update that module?

2020-09-28 19:50 UTC, shirleywbi approved these changes
Looks good.
![image](https://user-images.githubusercontent.com/45089842/94478983-ee4aed80-0188-11eb-8c5f-a7086d3390f0.png)

2020-10-01 02:34 UTC, wynnset approved these changes

2020-10-01 02:36 UTC, merged