746 - Bug fix: Adding child node makes it appear like a grandchild node
wynnset/tapestry-wp pull request #747
Opened 2020-09-16 21:11 UTC by narendrasss

Closes #746 

Changes the default depth to 3 rather than `maxDepth + 1` so that nodes made off an empty Tapestry wouldn't appear as grandchild nodes. I believe this also better reflects the old functionality in `tapestry.js`.

2020-09-22 06:28 UTC, seanRong commented
Looks good to me, definitely prefer this implementation

2020-09-22 18:26 UTC, yungalyx commented
nice fix!

2020-09-22 23:44 UTC, wynnset requested changes
Looks good just a small nit

2020-09-22 23:44 UTC, wynnset commented on templates/vue/src/components/TapestryDepthSlider.vue
> +      this.currentDepth = this.settings.defaultDepth || 3
`3` should be stored as a constant in the app or at minimum as a data variable. It's not a good idea to hard-code values in the code.

2020-09-24 18:37 UTC, narendrasss commented
@wynnset I updated the implementation to fill the default depth with the constant if it's undefined in settings. This should also fix the other issue I encountered in #624.

2020-09-24 20:00 UTC, wynnset approved these changes

2020-09-24 20:01 UTC, merged