823 - Cannot use Ctrl/Cmd + A to select all nodes if logged in
wynnset/tapestry-wp pull request #824
Opened 2020-10-26 17:21 UTC by seanRong

fixes #823 

Change from using mounted to using bv::modal to decide when to remove DragSelect's even listener in the settings modal in particular, as now the settings modal mounts immediately for logged in users and cannot be used to determine the visibility of the actual modal.

2020-10-26 17:33 UTC, shirleywbi approved these changes
LGTM

2020-10-26 17:57 UTC, narendrasss requested changes
Code looks good, can you add tests?

2020-11-02 17:05 UTC, seanRong commented
As discussed, we should leave the tests for now

2020-11-03 02:34 UTC, wynnset approved these changes

2020-11-03 02:41 UTC, merged